channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - pip
  - numpy
  - pandas
  - matplotlib
  - pytest
  - xarray
  - spatialdata
  - spatialdata-io
  - napari-spatialdata
  - spatialdata-plot
  - squidpy>=1.6.2
  - spatial-image
  - pip:
    - PyQt5 # for napari
    - lxml_html_clean # for napari
